---
# tasks file for Execute_Command
  - name: Execute any command
    command: "{{ command }}"
    args:
      warn: no
    register: command_result
  - debug:
      msg: command_result.stdout_lines

